/**
Copyright (c) 2011-present - Luu Gia Thuy

Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/

package com.luugiathuy.apps.downloadmanager.gui;

import java.awt.Color;
import java.net.URL;
import java.util.Observable;
import java.util.Observer;

import javax.annotation.PostConstruct;
import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.GroupLayout.SequentialGroup;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.luugiathuy.apps.downloader.Downloader;
import com.luugiathuy.apps.downloadmanager.DOWNLOAD_STATUS;
import com.luugiathuy.apps.downloadmanager.DownloadManager;
import com.luugiathuy.apps.downloadmanager.ProgressRenderer;

import lombok.extern.slf4j.Slf4j;

@Slf4j
@Component
public class DownloadManagerGUI extends javax.swing.JFrame implements Observer {

	private static final long serialVersionUID = 8489399426552541643L;

	@Autowired
	private DownloadTableModel mTableModel;

	private Downloader mSelectedDownloader;

	@Autowired
	private DownloadManager downloadManager;
	@Autowired
	private ButtonComponents buttonComponents;
	private boolean mIsClearing;

	private void initialize() {
		// Set up table
		jtbDownload.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent e) {
				tableSelectionChanged();
			}
		});

		// Allow only one row at a time to be selected.
		jtbDownload.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

		// Set up ProgressBar as renderer for progress column.
		ProgressRenderer renderer = new ProgressRenderer(0, 100);
		renderer.setStringPainted(true); // show progress text
		jtbDownload.setDefaultRenderer(JProgressBar.class, renderer);

		// Set table's row height large enough to fit JProgressBar.
		jtbDownload.setRowHeight((int) renderer.getPreferredSize().getHeight());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jtxURL = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		jtbDownload = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Download Manager");
		setResizable(false);

		initializeButtons();

		jtbDownload.setModel(mTableModel);
		jScrollPane1.setViewportView(jtbDownload);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		setHorizontalGroup(layout);

		buttonComponents.linkSize(layout);

		setVerticalGroup(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void setVerticalGroup(javax.swing.GroupLayout layout) {
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(createActingComponentsVertical(layout)));
	}

	private SequentialGroup createActingComponentsVertical(javax.swing.GroupLayout layout) {
		return layout.createSequentialGroup().addContainerGap()
				.addGroup(createTopPanelVertical(layout))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(buttonComponents.createBottomButtonPanelVertical(layout)).addContainerGap();
	}

	private ParallelGroup createTopPanelVertical(javax.swing.GroupLayout layout) {
		return layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
				.addComponent(jtxURL, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addComponent(buttonComponents.jbnAdd);
	}

	private void setHorizontalGroup(javax.swing.GroupLayout layout) {
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap().addGroup(createActingComponents(layout)).addContainerGap()));
	}

	private ParallelGroup createActingComponents(javax.swing.GroupLayout layout) {
		return layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(buttonComponents.createBottomButtonPanel(layout))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createTopPanelHorizontal(layout))
				.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE);
	}

	private SequentialGroup createTopPanelHorizontal(javax.swing.GroupLayout layout) {
		return layout.createSequentialGroup()
				.addComponent(jtxURL, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(buttonComponents.jbnAdd);
	}

	// Called when table row selection changes.
	private void tableSelectionChanged() {
		// unregister from receiving notifications from the last selected
		// download.
		if (mSelectedDownloader != null)
			mSelectedDownloader.deleteObserver(DownloadManagerGUI.this);

		// If not in the middle of clearing a download, set the selected
		// download and register to
		// receive notifications from it.
		if (!mIsClearing) {
			int index = jtbDownload.getSelectedRow();
			if (index != -1) {
				mSelectedDownloader = downloadManager.getDownload(jtbDownload.getSelectedRow());
				mSelectedDownloader.addObserver(DownloadManagerGUI.this);
			} else
				mSelectedDownloader = null;
			buttonComponents.updateButtons(mSelectedDownloader);
		}
	}

	@Override
	public void update(Observable o, Object arg) {
		// Update buttons if the selected download has changed.
		if (mSelectedDownloader != null && mSelectedDownloader.equals(o))
			buttonComponents.updateButtons(mSelectedDownloader);
	}

	private void initializeButtons() {
		buttonComponents.initAddButton(this::jbnAddActionPerformed);

		buttonComponents.initStartButton(this::jbnStartActionPerformed);

		buttonComponents.initPauseButton(this::jbnPauseActionPerformed);

		buttonComponents.initRemoveButton(this::jbnRemoveActionPerformed);

		buttonComponents.initCancelButton(this::jbnCancelActionPerformed);

		buttonComponents.initExitButton(this::jbnExitActionPerformed);

		buttonComponents.initResumeButton(this::jbnResumeActionPerformed);
	}

	private void jbnStartActionPerformed(java.awt.event.ActionEvent evt) {
		mSelectedDownloader.download();
		buttonComponents.updateButtons(mSelectedDownloader);
	}

	/**
	 * Update buttons' state
	 */
	private void jbnPauseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbnPauseActionPerformed
		mSelectedDownloader.pause();
		buttonComponents.updateButtons(mSelectedDownloader);
	}// GEN-LAST:event_jbnPauseActionPerformed

	private void jbnResumeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbnResumeActionPerformed
		mSelectedDownloader.resume();
		buttonComponents.updateButtons(mSelectedDownloader);
	}// GEN-LAST:event_jbnResumeActionPerformed

	private void jbnCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbnCancelActionPerformed
		mSelectedDownloader.cancel();
		buttonComponents.updateButtons(mSelectedDownloader);
	}// GEN-LAST:event_jbnCancelActionPerformed

	private void jbnRemoveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbnRemoveActionPerformed
		mIsClearing = true;
		int index = jtbDownload.getSelectedRow();
		downloadManager.removeDownload(index);
		mTableModel.clearDownload(index);
		mIsClearing = false;
		mSelectedDownloader = null;
		buttonComponents.updateButtons(mSelectedDownloader);
	}// GEN-LAST:event_jbnRemoveActionPerformed

	private void jbnExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbnExitActionPerformed
		setVisible(false);
	}// GEN-LAST:event_jbnExitActionPerformed

	private void jbnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbnAddActionPerformed
		URL verifiedUrl = DownloadManager.verifyURL(jtxURL.getText());
		if (verifiedUrl != null) {
			Downloader download = downloadManager.createDownload(verifiedUrl, DownloadManager.DEFAULT_OUTPUT_FOLDER);
			mTableModel.addNewDownload(download);
			jtxURL.setText(""); // reset add text field
		} else {
			JOptionPane.showMessageDialog(this, "Invalid Download URL", "Error", JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_jbnAddActionPerformed

	@PostConstruct
	public void postConstruct() {
		try {
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
			UIManager.put("ProgressBar.background", Color.ORANGE);
			UIManager.put("ProgressBar.foreground", Color.BLUE);
			UIManager.put("ProgressBar.selectionBackground", Color.RED);
			UIManager.put("ProgressBar.selectionForeground", Color.GREEN);
		} catch (Exception e) {
			log.error("look and feel could not intiated", e);
		}

		java.awt.EventQueue.invokeLater(() -> {
			this.setVisible(true);
			initComponents();
			initialize();
		});

	}

	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jtbDownload;
	private javax.swing.JTextField jtxURL;
}
